baseURL = "https://example.com"
languageCode = "en-us"
title = "Photography Club, IIIT-H"
theme = "showcase-hugo-theme"
themesDir = "themes"

[params]
  author = "Photography Club, IIIT-H"
  description = "Website for Photography Club, IIIT-H"
  message = ""
  hideAutoMenu = false

[[menu.main]]
  name = "External"
  url = "https://example.com"

[social]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
